package generator_test

import (
	"fmt"
	"strings"

	"github.com/DiLRandI/confgen/generator"
	"github.com/DiLRandI/confgen/schema"
)

func ExampleGenerate() {
	m, err := schema.Compile("config.schema.yaml", []byte("version: 1\npackage: appconfig\nfields: {port: {type: int, default: 8080}}"))
	if err != nil {
		panic(err)
	}
	code, err := generator.Generate(m, generator.Options{})
	if err != nil {
		panic(err)
	}
	fmt.Println(strings.HasPrefix(string(code), "// Code generated by configgen. DO NOT EDIT."))
	// Output: true
}
