package generator

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/DiLRandI/confgen/config"
	"github.com/DiLRandI/confgen/schema"
)

// Options configures generated runtime imports. An empty RuntimeImport uses
// github.com/DiLRandI/confgen/config.
type Options struct{ RuntimeImport string }

// Generate renders Go source from an immutable validated model. Output is
// deterministic, gofmt-formatted, and includes Load, LoadContext, and MustLoad.
func Generate(m *schema.Model, options Options) ([]byte, error) {
	if m == nil {
		return nil, fmt.Errorf("validated schema is nil")
	}
	runtimeImport := options.RuntimeImport
	if runtimeImport == "" {
		runtimeImport = "github.com/DiLRandI/confgen/config"
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by confgen. DO NOT EDIT.\n\npackage %s\n\nimport (\nconfigContext \"context\"\nconfigRuntime %q\n", m.Package, runtimeImport)
	hasDuration := false
	visit(m.Descriptor.Fields, func(f config.FieldDescriptor) {
		if f.Kind == config.KindDuration {
			hasDuration = true
		}
	})
	if hasDuration {
		fmt.Fprintln(&b, "configTime \"time\"")
	}
	fmt.Fprintln(&b, ")")
	var structs func(string, []config.FieldDescriptor)
	structs = func(name string, fields []config.FieldDescriptor) {
		fmt.Fprintf(&b, "\n// %s holds validated configuration values.\ntype %s struct {\n", name, name)
		for _, f := range fields {
			desc := m.Descriptions[f.Path]
			if desc = strings.TrimSpace(desc); desc != "" {
				if !strings.HasPrefix(desc, f.GoName+" ") {
					r, n := utf8.DecodeRuneInString(desc)
					next, _ := utf8.DecodeRuneInString(desc[n:])
					if !unicode.IsUpper(next) {
						r = unicode.ToLower(r)
					}
					desc = f.GoName + " is the " + string(r) + desc[n:]
				}
				for line := range strings.SplitSeq(strings.ReplaceAll(desc, "\r", ""), "\n") {
					fmt.Fprintf(&b, "// %s\n", line)
				}
			}
			fmt.Fprintf(&b, "%s %s `json:%q yaml:%q`\n", f.GoName, goType(m, f), f.ExternalKey(), f.ExternalKey())
		}
		fmt.Fprintln(&b, "}")
		for _, f := range fields {
			if f.Kind == config.KindObject {
				structs(m.TypeNames[f.Path], f.Children)
			}
			if f.Kind == config.KindList && f.Item != nil && f.Item.Kind == config.KindObject {
				structs(m.TypeNames[f.Item.Path], f.Item.Children)
			}
		}
	}
	structs(m.Name, m.Descriptor.Fields)
	fmt.Fprintf(&b, "\nvar configDescriptor = configRuntime.Descriptor{RootName:%q, EnvPrefix:%q, UnknownFields:%q, Fields: []configRuntime.FieldDescriptor{\n", m.Name, m.Descriptor.EnvPrefix, m.Descriptor.UnknownFields)
	for _, f := range m.Descriptor.Fields {
		renderField(&b, f)
	}
	fmt.Fprintln(&b, "}}")
	fmt.Fprintf(&b, `// Load composes sources in order; later sources win.
func Load(sources ...configRuntime.Source) (*%s, error) {
 return LoadContext(configContext.Background(), sources...)
}
// LoadContext loads and validates configuration, returning nil on failure.
func LoadContext(ctx configContext.Context, sources ...configRuntime.Source) (*%s, error) {
 return configRuntime.Load[%s](ctx, configDescriptor, sources...)
}
// MustLoad loads configuration and panics with the returned error on failure.
func MustLoad(sources ...configRuntime.Source) *%s {
 cfg, err := Load(sources...)
 if err != nil { panic(err) }
 return cfg
}
`, m.Name, m.Name, m.Name, m.Name)
	out, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated Go: %w", err)
	}
	return out, nil
}

func goType(m *schema.Model, f config.FieldDescriptor) string {
	switch f.Kind {
	case config.KindObject:
		return m.TypeNames[f.Path]
	case config.KindDuration:
		return "configTime.Duration"
	case config.KindPath:
		return "string"
	case config.KindList:
		return "[]" + goType(m, *f.Item)
	case config.KindMap:
		return "map[string]" + goType(m, *f.MapValue)
	default:
		return string(f.Kind)
	}
}

func visit(fields []config.FieldDescriptor, fn func(config.FieldDescriptor)) {
	for _, f := range fields {
		fn(f)
		visit(f.Children, fn)
		if f.Item != nil {
			visit([]config.FieldDescriptor{*f.Item}, fn)
		}
		if f.MapValue != nil {
			visit([]config.FieldDescriptor{*f.MapValue}, fn)
		}
	}
}

func renderField(b *bytes.Buffer, f config.FieldDescriptor) {
	fmt.Fprintf(b, "{Name:%q,", f.Name)
	if f.Key != "" {
		fmt.Fprintf(b, "Key:%q,", f.Key)
	}
	fmt.Fprintf(b, "Path:%q,GoName:%q,Kind:%q,Required:%t,Secret:%t,EnvName:%q,EnvDisabled:%t,GoIndex:[]int{", f.Path, f.GoName, f.Kind, f.Required, f.Secret, f.EnvName, f.EnvDisabled)
	for _, i := range f.GoIndex {
		fmt.Fprintf(b, "%d,", i)
	}
	fmt.Fprint(b, "},")
	if f.HasDefault {
		fmt.Fprintf(b, "HasDefault:true,Default:%s,", literal(f.Default))
	}
	c := f.Constraints
	fmt.Fprintf(b, "Constraints:configRuntime.Constraints{Min:%s,Max:%s,Pattern:%q,", literal(c.Min), literal(c.Max), c.Pattern)
	if c.MinLength != nil {
		fmt.Fprintf(b, "MinLength:new(%d),", *c.MinLength)
	}
	if c.MaxLength != nil {
		fmt.Fprintf(b, "MaxLength:new(%d),", *c.MaxLength)
	}
	if len(c.Enum) > 0 {
		fmt.Fprintf(b, "Enum:%s,", literal(c.Enum))
	}
	fmt.Fprint(b, "},")
	if len(f.Children) > 0 {
		fmt.Fprint(b, "Children:[]configRuntime.FieldDescriptor{")
		for _, c := range f.Children {
			renderField(b, c)
		}
		fmt.Fprint(b, "},")
	}
	if f.Item != nil {
		fmt.Fprint(b, "Item:&configRuntime.FieldDescriptor")
		renderFieldPointer(b, *f.Item)
	}
	if f.MapValue != nil {
		fmt.Fprint(b, "MapValue:&configRuntime.FieldDescriptor")
		renderFieldPointer(b, *f.MapValue)
	}
	fmt.Fprintln(b, "},")
}

func renderFieldPointer(b *bytes.Buffer, f config.FieldDescriptor) {
	var tmp bytes.Buffer
	renderField(&tmp, f)
	b.Write(tmp.Bytes())
}

func literal(v any) string {
	switch x := v.(type) {
	case nil:
		return "nil"
	case string:
		return strconv.Quote(x)
	case bool:
		return strconv.FormatBool(x)
	case int:
		if x < -1<<31 || x > 1<<31-1 {
			return fmt.Sprintf("int64(%d)", x)
		}
		return fmt.Sprintf("int(%d)", x)
	case int64:
		return fmt.Sprintf("int64(%d)", x)
	case uint:
		return fmt.Sprintf("uint(%d)", x)
	case uint64:
		return fmt.Sprintf("uint64(%d)", x)
	case float64:
		return "float64(" + strconv.FormatFloat(x, 'g', -1, 64) + ")"
	case []any:
		var b strings.Builder
		b.WriteString("[]any{")
		for _, v := range x {
			b.WriteString(literal(v) + ",")
		}
		b.WriteString("}")
		return b.String()
	case map[string]any:
		keys := make([]string, 0, len(x))
		for k := range x {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		var b strings.Builder
		b.WriteString("map[string]any{")
		for _, k := range keys {
			b.WriteString(strconv.Quote(k) + ":" + literal(x[k]) + ",")
		}
		b.WriteString("}")
		return b.String()
	default:
		panic(fmt.Sprintf("unsupported validated value %T", v))
	}
}
