// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package config_test

import (
	"context"

	"github.com/DiLRandI/confgen/config"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSource creates a new instance of MockSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSource {
	mock := &MockSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSource is an autogenerated mock type for the Source type
type MockSource struct {
	mock.Mock
}

type MockSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSource) EXPECT() *MockSource_Expecter {
	return &MockSource_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockSource
func (_mock *MockSource) Load(context1 context.Context, descriptor *config.Descriptor) (config.Document, error) {
	ret := _mock.Called(context1, descriptor)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 config.Document
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *config.Descriptor) (config.Document, error)); ok {
		return returnFunc(context1, descriptor)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *config.Descriptor) config.Document); ok {
		r0 = returnFunc(context1, descriptor)
	} else {
		r0 = ret.Get(0).(config.Document)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *config.Descriptor) error); ok {
		r1 = returnFunc(context1, descriptor)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSource_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockSource_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - context1 context.Context
//   - descriptor *config.Descriptor
func (_e *MockSource_Expecter) Load(context1 any, descriptor any) *MockSource_Load_Call {
	return &MockSource_Load_Call{Call: _e.mock.On("Load", context1, descriptor)}
}

func (_c *MockSource_Load_Call) Run(run func(context1 context.Context, descriptor *config.Descriptor)) *MockSource_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *config.Descriptor
		if args[1] != nil {
			arg1 = args[1].(*config.Descriptor)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSource_Load_Call) Return(document config.Document, err error) *MockSource_Load_Call {
	_c.Call.Return(document, err)
	return _c
}

func (_c *MockSource_Load_Call) RunAndReturn(run func(context1 context.Context, descriptor *config.Descriptor) (config.Document, error)) *MockSource_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockSource
func (_mock *MockSource) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSource_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockSource_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockSource_Expecter) Name() *MockSource_Name_Call {
	return &MockSource_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockSource_Name_Call) Run(run func()) *MockSource_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSource_Name_Call) Return(s string) *MockSource_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSource_Name_Call) RunAndReturn(run func() string) *MockSource_Name_Call {
	_c.Call.Return(run)
	return _c
}
