// Code generated by configgen. DO NOT EDIT.

package appconfig

import (
	configContext "context"
	configRuntime "go-config/config"
	configTime "time"
)

// Config holds validated configuration values.
type Config struct {
	// Server is the server configuration value.
	Server ServerConfig `json:"server" yaml:"server"`
	// Database is the database configuration value.
	Database DatabaseConfig `json:"database" yaml:"database"`
	// StorageDir is the storage_dir configuration value.
	StorageDir string `json:"storage_dir" yaml:"storage_dir"`
	// Debug is the debug configuration value.
	Debug bool `json:"debug" yaml:"debug"`
	// LogLevel is the log_level configuration value.
	LogLevel string `json:"log_level" yaml:"log_level"`
	// AllowedOrigins is the allowed_origins configuration value.
	AllowedOrigins []string `json:"allowed_origins" yaml:"allowed_origins"`
	// Labels is the labels configuration value.
	Labels map[string]string `json:"labels" yaml:"labels"`
}

// ServerConfig holds validated configuration values.
type ServerConfig struct {
	// Address the HTTP server binds to.
	Host string `json:"host" yaml:"host"`
	// HTTP listen port.
	Port int `json:"port" yaml:"port"`
	// Timeout is the server.timeout configuration value.
	Timeout configTime.Duration `json:"timeout" yaml:"timeout"`
}

// DatabaseConfig holds validated configuration values.
type DatabaseConfig struct {
	// URL is the database.url configuration value.
	URL string `json:"url" yaml:"url"`
}

var configDescriptor = configRuntime.Descriptor{RootName: "Config", EnvPrefix: "SHOP", UnknownFields: "error", Fields: []configRuntime.FieldDescriptor{
	{Name: "server", Path: "server", GoName: "Server", Kind: "object", Required: false, Secret: false, EnvName: "", EnvDisabled: false, GoIndex: []int{0}, Constraints: configRuntime.Constraints{Min: nil, Max: nil, Pattern: ""}, Children: []configRuntime.FieldDescriptor{{Name: "host", Path: "server.host", GoName: "Host", Kind: "string", Required: false, Secret: false, EnvName: "SHOP_SERVER_HOST", EnvDisabled: false, GoIndex: []int{0}, HasDefault: true, Default: "0.0.0.0", Constraints: configRuntime.Constraints{Min: nil, Max: nil, Pattern: ""}},
		{Name: "port", Path: "server.port", GoName: "Port", Kind: "int", Required: false, Secret: false, EnvName: "SHOP_SERVER_PORT", EnvDisabled: false, GoIndex: []int{1}, HasDefault: true, Default: int(8080), Constraints: configRuntime.Constraints{Min: int(1), Max: int(65535), Pattern: ""}},
		{Name: "timeout", Path: "server.timeout", GoName: "Timeout", Kind: "duration", Required: false, Secret: false, EnvName: "SHOP_SERVER_TIMEOUT", EnvDisabled: false, GoIndex: []int{2}, HasDefault: true, Default: "30s", Constraints: configRuntime.Constraints{Min: "100ms", Max: "5m", Pattern: ""}},
	}},
	{Name: "database", Path: "database", GoName: "Database", Kind: "object", Required: false, Secret: false, EnvName: "", EnvDisabled: false, GoIndex: []int{1}, Constraints: configRuntime.Constraints{Min: nil, Max: nil, Pattern: ""}, Children: []configRuntime.FieldDescriptor{{Name: "url", Path: "database.url", GoName: "URL", Kind: "string", Required: true, Secret: true, EnvName: "DATABASE_URL", EnvDisabled: false, GoIndex: []int{0}, Constraints: configRuntime.Constraints{Min: nil, Max: nil, Pattern: ""}}}},
	{Name: "storage_dir", Path: "storage_dir", GoName: "StorageDir", Kind: "path", Required: false, Secret: false, EnvName: "SHOP_STORAGE_DIR", EnvDisabled: false, GoIndex: []int{2}, HasDefault: true, Default: "./data", Constraints: configRuntime.Constraints{Min: nil, Max: nil, Pattern: ""}},
	{Name: "debug", Path: "debug", GoName: "Debug", Kind: "bool", Required: false, Secret: false, EnvName: "SHOP_DEBUG", EnvDisabled: false, GoIndex: []int{3}, HasDefault: true, Default: false, Constraints: configRuntime.Constraints{Min: nil, Max: nil, Pattern: ""}},
	{Name: "log_level", Path: "log_level", GoName: "LogLevel", Kind: "string", Required: false, Secret: false, EnvName: "SHOP_LOG_LEVEL", EnvDisabled: false, GoIndex: []int{4}, HasDefault: true, Default: "info", Constraints: configRuntime.Constraints{Min: nil, Max: nil, Pattern: "", Enum: []any{"debug", "info", "warn", "error"}}},
	{Name: "allowed_origins", Path: "allowed_origins", GoName: "AllowedOrigins", Kind: "list", Required: false, Secret: false, EnvName: "SHOP_ALLOWED_ORIGINS", EnvDisabled: false, GoIndex: []int{5}, Constraints: configRuntime.Constraints{Min: nil, Max: nil, Pattern: ""}, Item: &configRuntime.FieldDescriptor{Name: "", Path: "allowed_origins[]", GoName: "", Kind: "string", Required: false, Secret: false, EnvName: "", EnvDisabled: true, GoIndex: []int{}, Constraints: configRuntime.Constraints{Min: nil, Max: nil, Pattern: ""}}},
	{Name: "labels", Path: "labels", GoName: "Labels", Kind: "map", Required: false, Secret: false, EnvName: "SHOP_LABELS", EnvDisabled: false, GoIndex: []int{6}, Constraints: configRuntime.Constraints{Min: nil, Max: nil, Pattern: ""}, MapValue: &configRuntime.FieldDescriptor{Name: "", Path: "labels{}", GoName: "", Kind: "string", Required: false, Secret: false, EnvName: "", EnvDisabled: true, GoIndex: []int{}, Constraints: configRuntime.Constraints{Min: nil, Max: nil, Pattern: ""}}},
}}

// Load composes sources in order; later sources win.
func Load(sources ...configRuntime.Source) (*Config, error) {
	return LoadContext(configContext.Background(), sources...)
}

// LoadContext loads and validates configuration, returning nil on failure.
func LoadContext(ctx configContext.Context, sources ...configRuntime.Source) (*Config, error) {
	return configRuntime.Load[Config](ctx, configDescriptor, sources...)
}

// MustLoad loads configuration and panics with the returned error on failure.
func MustLoad(sources ...configRuntime.Source) *Config {
	cfg, err := Load(sources...)
	if err != nil {
		panic(err)
	}
	return cfg
}
